# Generated by Django 5.1.4 on 2024-12-26 04:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Laptop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "laptop_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=255)),
                ("brand", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("category", models.CharField(default="Laptops", max_length=255)),
                ("currency", models.CharField(default="USD", max_length=10)),
                ("processor", models.CharField(blank=True, max_length=255, null=True)),
                ("ram", models.CharField(blank=True, max_length=50, null=True)),
                ("storage", models.CharField(blank=True, max_length=50, null=True)),
                ("gpu", models.CharField(blank=True, max_length=255, null=True)),
                ("screen_size", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "discounted_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("stock", models.PositiveIntegerField()),
                (
                    "image1",
                    models.ImageField(
                        blank=True, null=True, upload_to="laptop_images/"
                    ),
                ),
                (
                    "image2",
                    models.ImageField(
                        blank=True, null=True, upload_to="laptop_images/"
                    ),
                ),
                (
                    "image3",
                    models.ImageField(
                        blank=True, null=True, upload_to="laptop_images/"
                    ),
                ),
                ("views", models.PositiveIntegerField(default=0)),
                ("purchases", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=255)),
                ("review_text", models.TextField()),
                ("review_date", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "laptop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="laptop_reviews",
                        to="allproduct.laptop",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="laptop",
            name="reviews",
            field=models.ManyToManyField(
                blank=True, related_name="laptops", to="allproduct.review"
            ),
        ),
        migrations.AddField(
            model_name="laptop",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="laptops", to="allproduct.tag"
            ),
        ),
    ]
