# Generated by Django 5.1.4 on 2024-12-26 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("allproduct", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="product",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="laptop_tags",
                to="allproduct.laptop",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
