# Generated by Django 5.1.4 on 2024-12-26 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("allproduct", "0002_tag_product_alter_tag_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="product",
        ),
    ]
