from django.db import models

class AcerLaptops(models.Model):
    html_filename = models.CharField(max_length=255, null=True, blank=True)
    image1 = models.URLField(max_length=500, null=True, blank=True)
    image2 = models.URLField(max_length=500, null=True, blank=True)
    image3 = models.URLField(max_length=500, null=True, blank=True)
    image4 = models.URLField(max_length=500, null=True, blank=True)
    product_title = models.CharField(max_length=255, null=True, blank=True)
    short_description = models.TextField(null=True, blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    brand = models.CharField(max_length=255, null=True, blank=True)
    series = models.CharField(max_length=255, null=True, blank=True)
    model = models.CharField(max_length=255, null=True, blank=True)
    processor = models.CharField(max_length=255, null=True, blank=True)
    generation__ _series = models.CharField(max_length=255, null=True, blank=True)
    memory = models.CharField(max_length=255, null=True, blank=True)
    memory_slots_available = models.CharField(max_length=255, null=True, blank=True)
    max_upgradable_memory = models.CharField(max_length=255, null=True, blank=True)
    display_size = models.CharField(max_length=255, null=True, blank=True)
    display_resolution = models.CharField(max_length=255, null=True, blank=True)
    display_type = models.CharField(max_length=255, null=True, blank=True)
    display_refresh_rate = models.CharField(max_length=255, null=True, blank=True)
    touch_screen_availability = models.CharField(max_length=255, null=True, blank=True)
    storage = models.CharField(max_length=255, null=True, blank=True)
    graphics = models.CharField(max_length=255, null=True, blank=True)
    battery = models.CharField(max_length=255, null=True, blank=True)
    ports_and_connectivity = models.CharField(max_length=255, null=True, blank=True)
    ethernet_&_bluetooth = models.CharField(max_length=255, null=True, blank=True)
    finger_print_reader = models.CharField(max_length=255, null=True, blank=True)
    speakers = models.CharField(max_length=255, null=True, blank=True)
    dimensions = models.CharField(max_length=255, null=True, blank=True)
    weight = models.CharField(max_length=255, null=True, blank=True)
    adapter_info = models.CharField(max_length=255, null=True, blank=True)
    color = models.CharField(max_length=255, null=True, blank=True)
    operating_system = models.CharField(max_length=255, null=True, blank=True)
    bundeled_software = models.CharField(max_length=255, null=True, blank=True)
    warranty_&_insurance = models.CharField(max_length=255, null=True, blank=True)
    bundeled_accessories = models.CharField(max_length=255, null=True, blank=True)
    emi_availability = models.CharField(max_length=255, null=True, blank=True)
    label = models.CharField(max_length=255, null=True, blank=True)
    description2 = models.TextField(null=True, blank=True)
    wireless_&_bluetooth = models.CharField(max_length=255, null=True, blank=True)
    audio = models.CharField(max_length=255, null=True, blank=True)
    display_size = models.CharField(max_length=255, null=True, blank=True)
    generation = models.CharField(max_length=255, null=True, blank=True)
    maximum_display_resolution = models.CharField(max_length=255, null=True, blank=True)
    operation_system = models.CharField(max_length=255, null=True, blank=True)
    processor_speed = models.CharField(max_length=255, null=True, blank=True)
    ram = models.CharField(max_length=255, null=True, blank=True)
    free_accessories = models.CharField(max_length=255, null=True, blank=True)
    touch_screen = models.CharField(max_length=255, null=True, blank=True)
    warranty = models.CharField(max_length=255, null=True, blank=True)
    unnamed:_50 = models.CharField(max_length=255, null=True, blank=True)
    ports_and_connectivity = models.CharField(max_length=255, null=True, blank=True)
    insurance = models.CharField(max_length=255, null=True, blank=True)
    operation_system = models.CharField(max_length=255, null=True, blank=True)
    warranty = models.CharField(max_length=255, null=True, blank=True)

    class Meta:
        verbose_name = "AcerLaptops"
        verbose_name_plural = "AcerLaptopss"

    def __str__(self):
        return self.product_title if hasattr(self, "product_title") else str(self.id)
